name: sliver_table
description: A table widget that can be used inside of a [CustomScrollView].
version: 0.0.2
homepage: https://github.com/omarsahl/
repository: https://github.com/omarsahl/sliver_table

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  linked_scroll_controller: ^0.2.0
  flutter_sticky_header: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
